spring:
  application.name: pincoin-spring
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://hostname:port/database"
    username: username
    password: password
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none # validate, create, create-drop., update, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 100
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  file:
    name: logs/spring.log
  level:
    kr.pincoin.api: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG

auth:
  jwt-secret-key: "openssl rand -hex 32"

security-config:
  content-security-policy: default-src 'none'
  cors:
    origins: "*"
    headers: "*"
    methods: "*"
    allow-credentials: true

aligo:
  api-key: api-key-issued-by-aligo
  user-id: user-id
  sender: 01012345678

line-notify:
  token: line-notify-token-issued-by-line
